name: AWS Secrets Manager

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::497241180797:role/test-role-github-oidc
          aws-region: ca-central-1

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Start Application in Background
        run: java -jar target/aws-vault-test-0.0.1-SNAPSHOT.jar
      
      - name: Get All Secret Names
        run: |
          echo "=== SECRET NAMES ==="
          curl -s http://localhost:8080/api/v1/secrets/names | jq .