name: AWS Secrets Manager

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      aws_role:
        description: 'Role to assume'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.event.inputs.aws_role }}
          aws-region: ca-central-1
          role-session-name: ${{ github.run_id }}-session

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Start Application
        run: java -jar target/aws-vault-test-0.0.1-SNAPSHOT.jar
